version: '3'
services:
  snmp-exporter:
    build: .
    image: ghcr.io/sebbegg/qnap-snmp-exporter
    command: ["--log.level=debug", "--config.file=/etc/snmp_exporter/snmp.yml"]
    ports:
      - 9116:9116